#!/usr/bin/env bash
#
# Serve the dev server over an HTTPS tunnel so a phone can sign in, and prove the
# tunnel actually reaches the app before printing the URL.
#
#   ./scripts/phone-preview.sh            # cloudflared, port 5173
#   ./scripts/phone-preview.sh --port 4173
#   ./scripts/phone-preview.sh --url https://example.ngrok-free.app   # verify only
#
# Why a tunnel and not `npm run dev -- --host` with the LAN IP: sign-in uses
# Amplify's SRP flow (`crypto.subtle`) and the share/upload links use
# `navigator.clipboard`. Browsers restrict both to a secure context, where
# `http://localhost` is an exception but `http://192.168.x.x` is not.
#
# The reason this script exists rather than two documented commands: every step
# below has failed at least once in a way that looked like the app being broken.
# Vite answering `Blocked request` for the tunnel hostname, a missing
# `amplify_outputs.json`, a tunnel URL printed before it resolves. Each is now
# checked and named.

set -euo pipefail

PORT=5173
TUNNEL_URL=""
START_TUNNEL=1

while [ $# -gt 0 ]; do
  case "$1" in
    --port) PORT="${2:?--port needs a value}"; shift 2 ;;
    --url)  TUNNEL_URL="${2:?--url needs a value}"; START_TUNNEL=0; shift 2 ;;
    -h|--help)
      cat <<'USAGE'
phone-preview.sh — serve the dev server over an HTTPS tunnel for phone testing,
and verify the tunnel reaches the app before printing the URL.

  ./scripts/phone-preview.sh                      cloudflared on port 5173
  ./scripts/phone-preview.sh --port 4173          a different port
  ./scripts/phone-preview.sh --url https://host   verify a tunnel you started

A phone cannot use http://<LAN-IP>: sign-in needs crypto.subtle and the share
links need navigator.clipboard, which browsers allow only in a secure context.
http://localhost is exempt, http://192.168.x.x is not. Hence HTTPS.

Prerequisites are checked on start, each with the command that fixes it.
Ctrl+C stops whatever this script started.
USAGE
      exit 0 ;;
    *) echo "unknown option: $1 (try --help)" >&2; exit 2 ;;
  esac
done

cd "$(dirname "$0")/.."

VITE_PID=""
TUNNEL_PID=""
TUNNEL_LOG=""

cleanup() {
  local code=$?
  # Kill only what this script started. A dev server that was already running
  # belongs to another terminal and must survive.
  [ -n "$TUNNEL_PID" ] && kill "$TUNNEL_PID" 2>/dev/null || true
  [ -n "$VITE_PID" ] && kill "$VITE_PID" 2>/dev/null || true
  [ -n "$TUNNEL_LOG" ] && rm -f "$TUNNEL_LOG" || true
  wait 2>/dev/null || true
  exit $code
}
trap cleanup EXIT INT TERM

fail() { echo "" >&2; echo "❌ $1" >&2; shift; for line in "$@"; do echo "   $line" >&2; done; exit 1; }

serving() { curl -sf -o /dev/null --max-time 3 "http://localhost:$PORT" 2>/dev/null; }

# ------------------------------------------------------------------
# Preflight. Each check names its own fix, so a failure here is actionable
# without opening the guide.
# ------------------------------------------------------------------
echo "▶ Preflight"

command -v node >/dev/null 2>&1 || fail "node not found." "Install Node.js 20 or newer: https://nodejs.org"
NODE_MAJOR="$(node --version | sed 's/^v\([0-9]*\).*/\1/')"
[ "$NODE_MAJOR" -ge 20 ] || fail "Node.js 20 or newer required (found $(node --version))."
echo "  ✔ node $(node --version)"

[ -d node_modules ] || fail "Dependencies not installed." "Run: npm install"
echo "  ✔ node_modules"

if [ ! -f amplify/portal-config.ts ]; then
  cp amplify/portal-config.example.ts amplify/portal-config.ts
  echo "  ✔ amplify/portal-config.ts created from the example (DemoMode: no ONTAP values)"
else
  echo "  ✔ amplify/portal-config.ts"
fi

# main.tsx imports this file statically, so Vite cannot serve the app without it.
# It is produced by a sandbox deploy and is gitignored, which is why a fresh
# clone reaches this line rather than a broken page on the phone.
[ -f amplify_outputs.json ] || fail \
  "amplify_outputs.json is missing, so the dev server cannot start." \
  "It is generated by a sandbox deploy and is gitignored (one per environment)." \
  "Run this once, in another terminal, and leave it running:" \
  "" \
  "    npx ampx sandbox" \
  "" \
  "It needs AWS credentials and takes a few minutes on a first run."
echo "  ✔ amplify_outputs.json"

if [ "$START_TUNNEL" -eq 1 ]; then
  command -v cloudflared >/dev/null 2>&1 || fail \
    "cloudflared not found." \
    "macOS:  brew install cloudflared" \
    "Linux:  https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/" \
    "" \
    "Or bring your own tunnel and let this script verify it:" \
    "    ./scripts/phone-preview.sh --url https://<your-tunnel-host>"
  echo "  ✔ cloudflared $(cloudflared --version 2>/dev/null | awk '{print $3}')"
fi

# ------------------------------------------------------------------
# Dev server. Reuse one that is already running; the guide tells you to start
# `npm start` in another terminal, and starting a second Vite would silently
# land on port 5174 while the tunnel keeps pointing at 5173.
# ------------------------------------------------------------------
echo ""
echo "▶ Dev server"
if serving; then
  echo "  ✔ already serving on http://localhost:$PORT (left running; not managed by this script)"
else
  echo "  … starting vite on port $PORT"
  npx vite --port "$PORT" --strictPort >/dev/null 2>&1 &
  VITE_PID=$!
  for _ in $(seq 1 40); do
    serving && break
    kill -0 "$VITE_PID" 2>/dev/null || fail \
      "vite exited before it started serving." \
      "Run it on its own to see the error: npx vite --port $PORT"
    sleep 0.5
  done
  serving || fail "vite did not answer on http://localhost:$PORT within 20s."
  echo "  ✔ serving on http://localhost:$PORT (pid $VITE_PID)"
fi

# ------------------------------------------------------------------
# Tunnel.
# ------------------------------------------------------------------
if [ "$START_TUNNEL" -eq 1 ]; then
  echo ""
  echo "▶ Tunnel"
  TUNNEL_LOG="$(mktemp -t phone-preview)"
  cloudflared tunnel --url "http://localhost:$PORT" >"$TUNNEL_LOG" 2>&1 &
  TUNNEL_PID=$!
  echo "  … waiting for cloudflared to publish a hostname"
  for _ in $(seq 1 60); do
    TUNNEL_URL="$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' "$TUNNEL_LOG" 2>/dev/null | head -1 || true)"
    [ -n "$TUNNEL_URL" ] && break
    kill -0 "$TUNNEL_PID" 2>/dev/null || { echo "--- cloudflared output ---" >&2; cat "$TUNNEL_LOG" >&2; fail "cloudflared exited before publishing a URL."; }
    sleep 0.5
  done
  [ -n "$TUNNEL_URL" ] || { echo "--- cloudflared output ---" >&2; cat "$TUNNEL_LOG" >&2; fail "no tunnel URL after 30s."; }
  echo "  ✔ $TUNNEL_URL"
fi

# ------------------------------------------------------------------
# Verify. The point of the script: a URL that returns Vite's host rejection
# looks exactly like a URL that works until you open it on the phone.
# ------------------------------------------------------------------
echo ""
echo "▶ Verify the tunnel reaches the app"

TUNNEL_HOST="${TUNNEL_URL#https://}"

# Stage 1: wait for the DNS record, asking a public resolver rather than this
# machine's.
#
# This is not a detail. cloudflared prints the hostname before it is resolvable
# ("it may take some time to be reachable"), and asking the local resolver that
# early caches the NXDOMAIN. Home-router resolvers hold a negative answer for
# minutes, so the machine that created the tunnel then cannot reach it long
# after it is live everywhere else -- observed here as over two minutes of
# "Could not resolve host" while 1.1.1.1 and 8.8.8.8 both had the record.
#
# Querying a public resolver leaves the local cache untouched, so the first
# local lookup happens only once there is a positive answer to cache.
DNS_PROBE=""
if command -v dig >/dev/null 2>&1; then
  DNS_PROBE="dig"
elif command -v host >/dev/null 2>&1; then
  DNS_PROBE="host"
fi

dns_published() {
  case "$DNS_PROBE" in
    dig)  [ -n "$(dig +short +time=2 +tries=1 @1.1.1.1 "$TUNNEL_HOST" A 2>/dev/null | grep -E '^[0-9.]+$' || true)" ] ;;
    host) host -W 2 "$TUNNEL_HOST" 1.1.1.1 >/dev/null 2>&1 ;;
    *)    return 2 ;;
  esac
}

DNS_BUDGET_S=180
if [ -z "$DNS_PROBE" ]; then
  # No resolver tool to ask, so the only safe move is to not look too early.
  echo "  … no dig/host available; waiting 45s before the first lookup"
  sleep 45
else
  DNS_DEADLINE=$(( $(date +%s) + DNS_BUDGET_S ))
  printf '  … waiting for DNS to publish %s ' "$TUNNEL_HOST"
  while :; do
    dns_published && break
    if [ "$(date +%s)" -ge "$DNS_DEADLINE" ]; then
      printf '\n'
      fail "the tunnel hostname was still not in public DNS after ${DNS_BUDGET_S}s." \
        "$TUNNEL_URL" \
        "" \
        "cloudflared registered the tunnel, so this is Cloudflare-side propagation," \
        "not the app. Run the script again to get a new hostname."
    fi
    printf '%s' "."
    sleep 3
  done
  printf ' ✔\n'
fi

# Stage 2: fetch it. Now that a positive record exists, a local lookup is safe.
BODY=""
STATUS=""
HTTP_BUDGET_S=90
HTTP_DEADLINE=$(( $(date +%s) + HTTP_BUDGET_S ))
printf '  … fetching '
while :; do
  # Body and status from one response: two separate curls can disagree.
  RESPONSE="$(curl -sS --max-time 5 -w '\n%{http_code}' "$TUNNEL_URL" 2>/dev/null || true)"
  STATUS="${RESPONSE##*$'\n'}"
  BODY="${RESPONSE%$'\n'*}"
  [ "$STATUS" = "200" ] && break
  # A host rejection is a settled answer, not a slow one. Retrying it for
  # minutes would bury the one message worth reading.
  case "$BODY" in *"Blocked request"*) break ;; esac
  [ "$(date +%s)" -ge "$HTTP_DEADLINE" ] && break
  printf '%s' "."
  sleep 3
done
printf '\n'

case "$BODY" in
  *"Blocked request"*)
    fail "Vite refused the tunnel hostname." \
      "It answered \"Blocked request\" for: $TUNNEL_HOST" \
      "" \
      "Vite only answers for hostnames it recognises, which is what stops a" \
      "malicious page from rebinding DNS to your dev server. Add the domain to" \
      "server.allowedHosts in vite.config.ts (a leading dot matches subdomains):" \
      "" \
      "    allowedHosts: [\".trycloudflare.com\", \".ngrok-free.app\", ...]" \
      "" \
      "Do not set it to true: that gives up the protection whenever the dev" \
      "server runs, tunnel or not."
    ;;
esac

if [ "$STATUS" = "000" ]; then
  # Public DNS has the record (stage 1 passed) but this machine cannot resolve
  # it. Almost always a negative answer cached before the record existed. The
  # tunnel is live; only this machine is blind to it, so the phone -- on a
  # different resolver, especially on cellular -- will very likely be fine.
  echo "  ⚠ this machine cannot resolve $TUNNEL_HOST, but public DNS can." >&2
  echo "" >&2
  echo "    The tunnel is live. Your resolver is holding a negative answer from" >&2
  echo "    before the record existed. The phone uses its own resolver, so try" >&2
  echo "    the URL there -- it will most likely load." >&2
  echo "" >&2
  echo "    To fix this machine (macOS):" >&2
  echo "      sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder" >&2
  echo "" >&2
  echo "    Skipping the remaining local checks; the URL is printed below." >&2
  SKIP_BODY_CHECK=1
elif [ "$STATUS" = "502" ] || [ "$STATUS" = "503" ]; then
  fail "the tunnel is up but could not reach http://localhost:$PORT (HTTP $STATUS)." \
    "The dev server stopped, or it is listening on a different port." \
    "Check it directly:  curl -I http://localhost:$PORT"
fi

if [ "${SKIP_BODY_CHECK:-0}" != "1" ]; then
  [ "$STATUS" = "200" ] || fail "the tunnel answered HTTP $STATUS, not 200." "Body: $(printf '%.200s' "$BODY")"

  case "$BODY" in
    *'id="root"'*) : ;;
    *) fail "the tunnel answered 200 but the body is not the portal." "Body: $(printf '%.200s' "$BODY")" ;;
  esac
  echo "  ✔ HTTP 200 and the page is the portal"
fi

# ------------------------------------------------------------------
echo ""
echo "════════════════════════════════════════════════════════"
echo "  Open on the phone:"
echo ""
echo "    $TUNNEL_URL"
echo ""
if command -v qrencode >/dev/null 2>&1; then
  qrencode -t ANSIUTF8 -m 1 "$TUNNEL_URL"
else
  echo "  (brew install qrencode to print a scannable QR code here)"
fi
echo "════════════════════════════════════════════════════════"
echo ""
echo "  The hostname changes on every run, so this URL is for your own device."
echo "  Anyone with it reaches your dev server while this runs. Ctrl+C to stop."
echo ""

if [ "$START_TUNNEL" -eq 1 ]; then
  wait "$TUNNEL_PID"
elif [ -n "$VITE_PID" ]; then
  wait "$VITE_PID"
fi
