#!/bin/bash
# =============================================================================
# SnapMirror 関係セットアップガイド（実行するコマンドの生成）
#
# オンプレミス ONTAP と FSx for ONTAP 間の SnapMirror 関係を作成する手順を表示
# =============================================================================
set -euo pipefail

# --- 設定 ---
SRC_CLUSTER="${SRC_CLUSTER:-onprem-cluster}"
SRC_SVM="${SRC_SVM:-svm_src}"
SRC_VOLUME="${SRC_VOLUME:-vol_demo}"
DST_SVM="${DST_SVM:-svm_demo}"
DST_VOLUME="${DST_VOLUME:-vol_demo}"
FSX_MGMT_IP="${FSX_MGMT_IP:-}"
FSX_INTERCLUSTER_IP="${FSX_INTERCLUSTER_IP:-}"
ONPREM_INTERCLUSTER_IP="${ONPREM_INTERCLUSTER_IP:-}"

echo "============================================"
echo "  SnapMirror Relationship Setup Guide"
echo "============================================"
echo ""
echo "  Source:      ${SRC_SVM}:${SRC_VOLUME} (On-Premises)"
echo "  Destination: ${DST_SVM}:${DST_VOLUME} (FSx for ONTAP)"
echo ""
echo "────────────────────────────────────────────"
echo ""

# --- Step 1: Cluster Peering ---
echo "📝 Step 1: Cluster Peering"
echo ""
echo "  [オンプレミス ONTAP CLI]"
echo "  cluster peer create \\"
echo "    -generate-passphrase \\"
echo "    -peer-addrs ${FSX_INTERCLUSTER_IP}"
echo ""
echo "  → 生成されたパスフレーズをメモ"
echo ""
echo "  [FSx ONTAP CLI (SSH: fsxadmin@${FSX_MGMT_IP})]"
echo "  cluster peer create \\"
echo "    -peer-addrs ${ONPREM_INTERCLUSTER_IP} \\"
echo "    -passphrase <上記のパスフレーズ>"
echo ""
echo "  確認:"
echo "  cluster peer show"
echo ""

# --- Step 2: SVM Peering ---
echo "────────────────────────────────────────────"
echo "📝 Step 2: SVM (Vserver) Peering"
echo ""
echo "  [オンプレミス ONTAP CLI]"
echo "  vserver peer create \\"
echo "    -vserver ${SRC_SVM} \\"
echo "    -peer-vserver ${DST_SVM} \\"
echo "    -peer-cluster <FSx_Cluster_Name> \\"
echo "    -applications snapmirror"
echo ""
echo "  [FSx ONTAP CLI]"
echo "  vserver peer accept \\"
echo "    -vserver ${DST_SVM} \\"
echo "    -peer-vserver ${SRC_SVM}"
echo ""
echo "  確認:"
echo "  vserver peer show"
echo ""

# --- Step 3: SnapMirror 関係作成 ---
echo "────────────────────────────────────────────"
echo "📝 Step 3: SnapMirror 関係の作成"
echo ""
echo "  ⚠️  FSx 側のボリュームは DP (Data Protection) タイプで作成済みの場合:"
echo ""
echo "  [FSx ONTAP CLI]"
echo "  snapmirror create \\"
echo "    -source-path ${SRC_SVM}:${SRC_VOLUME} \\"
echo "    -destination-path ${DST_SVM}:${DST_VOLUME} \\"
echo "    -type XDP \\"
echo "    -policy MirrorAllSnapshots"
echo ""
echo "  # 初期転送（ベースライン）"
echo "  snapmirror initialize \\"
echo "    -destination-path ${DST_SVM}:${DST_VOLUME}"
echo ""
echo "  確認:"
echo "  snapmirror show -destination-path ${DST_SVM}:${DST_VOLUME}"
echo ""

# --- Step 4: REST API で UUID 取得 ---
echo "────────────────────────────────────────────"
echo "📝 Step 4: SnapMirror UUID の取得（Sync Server 設定用）"
echo ""
echo "  [ローカル PC から実行]"
echo "  curl -k -u fsxadmin:<password> \\"
echo "    'https://${FSX_MGMT_IP}/api/snapmirror/relationships' \\"
echo "    | python3 -m json.tool"
echo ""
echo "  → レスポンスの uuid フィールドを .env に設定"
echo "  SNAPMIRROR_UUID=<取得した UUID>"
echo ""

# --- Step 5: 定期スケジュール設定 ---
echo "────────────────────────────────────────────"
echo "📝 Step 5: 定期スケジュールの設定"
echo ""
echo "  SnapMirror は定期スケジュール（自動）とワンクリック（手動割り込み）を"
echo "  組み合わせて使用します。"
echo ""
echo "  [FSx ONTAP CLI]"
echo "  # デモ用に 5 分間隔のスケジュールを作成"
echo "  job schedule cron create -name 5min -minute 0,5,10,15,20,25,30,35,40,45,50,55"
echo ""
echo "  # SnapMirror 関係にスケジュールを適用"
echo "  snapmirror modify -destination-path ${DST_SVM}:${DST_VOLUME} -schedule 5min"
echo ""
echo "  # 確認"
echo "  snapmirror show -destination-path ${DST_SVM}:${DST_VOLUME} -fields schedule"
echo ""
echo "  [REST API で設定する場合]"
echo "  curl -k -u fsxadmin:<password> -X PATCH \\"
echo "    'https://${FSX_MGMT_IP}/api/snapmirror/relationships/<UUID>' \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"transfer_schedule\": {\"name\": \"5min\"}}'"
echo ""
echo "  ─────────────────────────────────"
echo "  定期スケジュールの選択ガイド:"
echo "  ・1分間隔:  ほぼリアルタイム（ONTAP 負荷大）"
echo "  ・5分間隔:  デモ推奨（ワンクリックと組み合わせて最適）"
echo "  ・15分間隔: 通常用途（ワンクリックがほぼ必須）"
echo ""
echo "  詳細: docs/snapmirror-schedule-ja.md"
echo ""

# --- Step 6: 手動テスト ---
echo "────────────────────────────────────────────"
echo "📝 Step 6: 手動同期テスト（= ワンクリックと同じ動作）"
echo ""
echo "  以下は、ワンクリックツールが内部で実行するのと同じ操作です:"
echo ""
echo "  [ONTAP CLI]"
echo "  snapmirror update -destination-path ${DST_SVM}:${DST_VOLUME}"
echo ""
echo "  [REST API — ワンクリックツールと同じ呼び出し]"
echo "  curl -k -u fsxadmin:<password> -X POST \\"
echo "    'https://${FSX_MGMT_IP}/api/snapmirror/relationships/<UUID>/transfers' \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{}'"
echo ""
echo "  → HTTP 202 Accepted が返ればトリガー成功"
echo "  → 定期スケジュール実行中に叩くと HTTP 409 (正常動作)"
echo ""
echo "============================================"
echo "  SnapMirror セットアップ手順の出力完了"
echo "============================================"
echo ""
echo "  ✅ 定期スケジュール: 5分毎に自動で増分同期"
echo "  ✅ ワンクリック:     任意のタイミングで即時割り込み同期"
echo ""
echo "  ⚠️  重要: SnapMirror 関係が Idle 状態になったら"
echo "  Sync Server の .env に UUID を設定して起動してください"
