#!/usr/bin/env python3
"""
Batch translation file generator for all UC architecture documents.
Generates English translations from Japanese sources, and 6 additional language
translations from English sources.

Usage: python3 scripts/batch_translate.py
"""
import os
import re
import json

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# UC definitions: (dir_name, uc_number, title_ja, title_en, title_ko, title_zh_cn, title_zh_tw, title_fr, title_de, title_es)
UCS = [
    ("legal-compliance", "UC1", 
     "法務・コンプライアンス — ファイルサーバー監査・データガバナンス",
     "Legal / Compliance — File Server Audit & Data Governance",
     "법무 / 컴플라이언스 — 파일 서버 감사 및 데이터 거버넌스",
     "法务 / 合规 — 文件服务器审计与数据治理",
     "法務 / 合規 — 檔案伺服器稽核與資料治理",
     "Juridique / Conformité — Audit de serveur de fichiers et gouvernance des données",
     "Recht / Compliance — Dateiserver-Audit & Datengovernance",
     "Legal / Cumplimiento — Auditoría de servidor de archivos y gobernanza de datos"),
    ("financial-idp", "UC2",
     "金融・保険 — 契約書・請求書の自動処理 (IDP)",
     "Finance / Insurance — Automated Contract & Invoice Processing (IDP)",
     "금융 / 보험 — 계약서 및 청구서 자동 처리 (IDP)",
     "金融 / 保险 — 合同与发票自动处理 (IDP)",
     "金融 / 保險 — 合約與發票自動處理 (IDP)",
     "Finance / Assurance — Traitement automatisé des contrats et factures (IDP)",
     "Finanzen / Versicherung — Automatisierte Vertrags- und Rechnungsverarbeitung (IDP)",
     "Finanzas / Seguros — Procesamiento automatizado de contratos y facturas (IDP)"),
    ("manufacturing-analytics", "UC3",
     "製造業 — IoT センサーログ・品質検査画像の分析",
     "Manufacturing — IoT Sensor Log & Quality Inspection Image Analysis",
     "제조업 — IoT 센서 로그 및 품질 검사 이미지 분석",
     "制造业 — IoT 传感器日志与质量检测图像分析",
     "製造業 — IoT 感測器日誌與品質檢測影像分析",
     "Industrie — Analyse des journaux de capteurs IoT et images d'inspection qualité",
     "Fertigung — IoT-Sensorprotokoll- und Qualitätsinspektionsbild-Analyse",
     "Manufactura — Análisis de registros de sensores IoT e imágenes de inspección de calidad"),
    ("media-vfx", "UC4",
     "メディア — VFX レンダリングパイプライン",
     "Media — VFX Rendering Pipeline",
     "미디어 — VFX 렌더링 파이프라인",
     "媒体 — VFX 渲染管线",
     "媒體 — VFX 算繪管線",
     "Médias — Pipeline de rendu VFX",
     "Medien — VFX-Rendering-Pipeline",
     "Medios — Pipeline de renderizado VFX"),
    ("healthcare-dicom", "UC5",
     "医療 — DICOM 画像の自動分類・匿名化",
     "Healthcare — DICOM Image Auto-Classification & Anonymization",
     "의료 — DICOM 이미지 자동 분류 및 익명화",
     "医疗 — DICOM 图像自动分类与匿名化",
     "醫療 — DICOM 影像自動分類與匿名化",
     "Santé — Classification automatique et anonymisation d'images DICOM",
     "Gesundheitswesen — Automatische DICOM-Bildklassifizierung und Anonymisierung",
     "Salud — Clasificación automática y anonimización de imágenes DICOM"),
    ("genomics-pipeline", "UC7",
     "ゲノミクス / バイオインフォマティクス — 品質チェック・バリアントコール集計",
     "Genomics / Bioinformatics — Quality Check & Variant Call Aggregation",
     "유전체학 / 생물정보학 — 품질 검사 및 변이 호출 집계",
     "基因组学 / 生物信息学 — 质量检查与变异调用汇总",
     "基因體學 / 生物資訊學 — 品質檢查與變異呼叫彙總",
     "Génomique / Bio-informatique — Contrôle qualité et agrégation des appels de variants",
     "Genomik / Bioinformatik — Qualitätsprüfung und Varianten-Call-Aggregation",
     "Genómica / Bioinformática — Control de calidad y agregación de llamadas de variantes"),
    ("energy-seismic", "UC8",
     "エネルギー / 石油・ガス — 地震探査データ処理・坑井ログ異常検知",
     "Energy / Oil & Gas — Seismic Data Processing & Well Log Anomaly Detection",
     "에너지 / 석유·가스 — 탄성파 탐사 데이터 처리 및 시추공 로그 이상 감지",
     "能源 / 石油天然气 — 地震勘探数据处理与井日志异常检测",
     "能源 / 石油天然氣 — 地震探勘資料處理與井日誌異常偵測",
     "Énergie / Pétrole et gaz — Traitement des données sismiques et détection d'anomalies des diagraphies",
     "Energie / Öl & Gas — Seismische Datenverarbeitung und Bohrloch-Log-Anomalieerkennung",
     "Energía / Petróleo y gas — Procesamiento de datos sísmicos y detección de anomalías en registros de pozos"),
    ("autonomous-driving", "UC9",
     "自動運転 / ADAS — 映像・LiDAR 前処理・品質チェック・アノテーション",
     "Autonomous Driving / ADAS — Video & LiDAR Preprocessing, Quality Check & Annotation",
     "자율주행 / ADAS — 영상 및 LiDAR 전처리, 품질 검사, 어노테이션",
     "自动驾驶 / ADAS — 视频与 LiDAR 预处理、质量检查与标注",
     "自動駕駛 / ADAS — 影片與 LiDAR 前處理、品質檢查與標註",
     "Conduite autonome / ADAS — Prétraitement vidéo et LiDAR, contrôle qualité et annotation",
     "Autonomes Fahren / ADAS — Video- und LiDAR-Vorverarbeitung, Qualitätsprüfung und Annotation",
     "Conducción autónoma / ADAS — Preprocesamiento de video y LiDAR, control de calidad y anotación"),
    ("construction-bim", "UC10",
     "建設 / AEC — BIM モデル管理・図面 OCR・安全コンプライアンス",
     "Construction / AEC — BIM Model Management, Drawing OCR & Safety Compliance",
     "건설 / AEC — BIM 모델 관리, 도면 OCR 및 안전 컴플라이언스",
     "建筑 / AEC — BIM 模型管理、图纸 OCR 与安全合规",
     "建築 / AEC — BIM 模型管理、圖面 OCR 與安全合規",
     "Construction / AEC — Gestion de modèles BIM, OCR de plans et conformité sécurité",
     "Bauwesen / AEC — BIM-Modellverwaltung, Zeichnungs-OCR und Sicherheits-Compliance",
     "Construcción / AEC — Gestión de modelos BIM, OCR de planos y cumplimiento de seguridad"),
    ("retail-catalog", "UC11",
     "小売 / EC — 商品画像自動タグ付け・カタログメタデータ生成",
     "Retail / E-Commerce — Product Image Auto-Tagging & Catalog Metadata Generation",
     "소매 / 전자상거래 — 상품 이미지 자동 태깅 및 카탈로그 메타데이터 생성",
     "零售 / 电商 — 商品图像自动标签与目录元数据生成",
     "零售 / 電商 — 商品影像自動標籤與目錄中繼資料產生",
     "Commerce / E-commerce — Étiquetage automatique d'images produits et génération de métadonnées catalogue",
     "Einzelhandel / E-Commerce — Automatisches Produkt-Bild-Tagging und Katalog-Metadaten-Generierung",
     "Retail / Comercio electrónico — Etiquetado automático de imágenes de productos y generación de metadatos de catálogo"),
    ("logistics-ocr", "UC12",
     "物流 / サプライチェーン — 配送伝票 OCR・倉庫在庫画像分析",
     "Logistics / Supply Chain — Shipping Slip OCR & Warehouse Inventory Image Analysis",
     "물류 / 공급망 — 배송 전표 OCR 및 창고 재고 이미지 분석",
     "物流 / 供应链 — 配送单据 OCR 与仓库库存图像分析",
     "物流 / 供應鏈 — 配送單據 OCR 與倉庫庫存影像分析",
     "Logistique / Chaîne d'approvisionnement — OCR de bordereaux d'expédition et analyse d'images d'inventaire",
     "Logistik / Lieferkette — Lieferschein-OCR und Lagerbestandsbild-Analyse",
     "Logística / Cadena de suministro — OCR de albaranes y análisis de imágenes de inventario de almacén"),
    ("education-research", "UC13",
     "教育 / 研究 — 論文 PDF 自動分類・引用ネットワーク分析",
     "Education / Research — Paper PDF Auto-Classification & Citation Network Analysis",
     "교육 / 연구 — 논문 PDF 자동 분류 및 인용 네트워크 분석",
     "教育 / 研究 — 论文 PDF 自动分类与引用网络分析",
     "教育 / 研究 — 論文 PDF 自動分類與引用網路分析",
     "Éducation / Recherche — Classification automatique de PDF d'articles et analyse de réseau de citations",
     "Bildung / Forschung — Automatische PDF-Klassifizierung und Zitationsnetzwerk-Analyse",
     "Educación / Investigación — Clasificación automática de PDF de artículos y análisis de redes de citación"),
    ("insurance-claims", "UC14",
     "保険 / 損害査定 — 事故写真損害評価・見積書 OCR・査定レポート",
     "Insurance / Claims — Accident Photo Damage Assessment, Estimate OCR & Assessment Report",
     "보험 / 손해 사정 — 사고 사진 손해 평가, 견적서 OCR 및 사정 보고서",
     "保险 / 理赔 — 事故照片损害评估、估价单 OCR 与理赔报告",
     "保險 / 理賠 — 事故照片損害評估、估價單 OCR 與理賠報告",
     "Assurance / Sinistres — Évaluation des dommages par photo, OCR de devis et rapport d'expertise",
     "Versicherung / Schadenregulierung — Unfallbild-Schadensbewertung, Kostenvoranschlag-OCR und Gutachten",
     "Seguros / Siniestros — Evaluación de daños por foto de accidente, OCR de presupuestos e informe de peritaje"),
]

print(f"UC definitions loaded: {len(UCS)} use cases")
print("Titles ready for all 8 languages.")
for uc in UCS:
    print(f"  {uc[1]}: {uc[0]} -> {uc[3]}")
