#!/usr/bin/env python3
"""Hold cdk-nag to a baseline, so a new finding fails instead of joining a pile.

Why a baseline rather than a clean run
--------------------------------------
cdk-nag reported 108 findings on the portal backend and nothing consumed the number, so
it was a report nobody read. Two of the categories were fixed rather than recorded
(point-in-time recovery on the two tables holding authored content, and a TLS-only policy
on the alarm topic). The rest need either a decision that cannot be validated without
deploying, or a change to a resource Amplify owns.

Recording them makes the remainder blocking: a finding that is not in the baseline fails,
and a baseline entry that is no longer reported also fails, so the file cannot drift
upward or hide progress. Same shape as `scripts/check_cfn_guard.py`.

What this does not claim
------------------------
A baselined finding is not a fixed finding. The `REASONS` table below says which
category each belongs to and why it is where it is; "Amplify owns the resource" and "we
own it and have not narrowed it yet" are different statements and are kept apart.

Running it
----------
    python3 scripts/check_cdk_nag_baseline.py            # blocking
    python3 scripts/check_cdk_nag_baseline.py --list     # what is reported now
    python3 scripts/check_cdk_nag_baseline.py --write    # rewrite the baseline file

`--write` is for after a deliberate change. Read the diff: it is the only place a new
finding can enter without failing.

The report comes from `solutions/amplify-portal/scripts/cdk-nag.sh` (`npm run nag`), which
synthesises without deploying. This script runs it when the report is missing or stale.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PORTAL = ROOT / "solutions" / "amplify-portal"
REPORT = PORTAL / ".cdk-nag-out" / "validation-report.json"
BASELINE = ROOT / "security" / "cdk-nag-baseline.txt"

# Which category a construct path belongs to, and why its findings are recorded rather
# than fixed. Ordered: the first matching prefix wins.
#
# Written as categories rather than per-finding notes because the findings arrive in
# groups -- nineteen Lambda roles carry the same managed policy for the same reason -- and
# a hundred copies of one sentence is not more informative than one.
REASONS: list[tuple[str, str]] = [
    # Before the generic `auth/` entry below, which would otherwise claim these are
    # Cognito settings Amplify owns. They are our own grant, on roles Amplify creates but
    # `backend.ts` fills in, and saying otherwise would misattribute eighteen findings.
    (
        "auth/amplifyAuth/authenticatedUserRole",
        "The Storage Browser's S3 scope, which is `s3ApResourceArns` from "
        "`portal-config.ts`. The account and region are filled in from the deployment, so "
        "what remains wildcarded is the access point name and the object key. A key cannot "
        "be enumerated in advance; an access-point wildcard is refused at synth once "
        "`groupApMapping` is in use.",
    ),
    (
        "GroupRole",
        "A Cognito group role, whose S3 grant `backend.ts` writes from `s3ApResourceArns` "
        "-- see `amplify/direct-s3-access.ts` for which group gets what. Same wildcards as "
        "the authenticated role above, and the same reasons.",
    ),
    (
        "auth/",
        "Cognito configured by Amplify `defineAuth`. MFA is a deployment choice exposed "
        "as `signIn.mfa`; the advanced-security and password-policy rules cover settings "
        "Amplify does not surface.",
    ),
    (
        "data/amplifyData",
        "AppSync and its table manager are generated by Amplify `defineData`. The "
        "wildcards are in roles Amplify writes, scoped to resources whose names are only "
        "known at deploy time.",
    ),
    (
        "data/AmplifyTableManager",
        "Same as data/amplifyData: an Amplify-generated custom resource.",
    ),
    (
        "data/Custom::CDK",
        "A CDK-internal custom resource (bucket deployment, log retention). Its role is "
        "written by the construct library.",
    ),
    (
        "data/LogRetention",
        "A CDK-internal custom resource. Its role is written by the construct library.",
    ),
    (
        "data/ChatHistoryTable",
        "No point-in-time recovery, deliberately: the rows carry a TTL and are chat "
        "history the portal regenerates as people use it. The two tables holding authored "
        "content -- agent definitions and team compositions -- do have it.",
    ),
    (
        "data/PortalSettingsTable",
        "No point-in-time recovery, deliberately: the table holds feature gates, so "
        "losing it resets them to their defaults and an administrator sets them again.",
    ),
    # The roles below hold a wildcard for a reason specific to the actions in them, so they
    # come before the `data/` catch-all. Each names the action that forces it, checked
    # against the service authorization reference on 2026-08-28 rather than assumed: an
    # action that defines no resource type cannot be scoped, and a policy that tries reads
    # as least privilege while denying every call.
    (
        "data/ComprehendLambdaRole",
        "`comprehend:DetectSentiment` and `DetectKeyPhrases` define no resource type, and "
        "`DetectEntities` defines only an optional custom `entity-recognizer-endpoint` this "
        "portal does not create. There is nothing to name.",
    ),
    (
        "data/DetectLabelsLambdaRole",
        "`rekognition:DetectLabels` takes image bytes or an S3 reference rather than a "
        "resource; AWS's own identity-based policy example for it grants `*`. The S3 read "
        "beside it is scoped to `s3ApResourceArns`.",
    ),
    (
        "data/TextractLambdaRole",
        "`textract:DetectDocumentText` and `AnalyzeDocument` define only `adapter` and "
        "`adapterversion`, neither of which this portal creates. The S3 read beside it is "
        "scoped to `s3ApResourceArns`.",
    ),
    (
        "data/PlatformDiscoveryFunction",
        "`fsx:DescribeFileSystems`, `fsx:DescribeStorageVirtualMachines` and "
        "`ec2:DescribeRegions` define no resource type -- they enumerate, and an "
        "enumeration cannot be restricted to the resources it is meant to find. The "
        "cross-account `sts:AssumeRole` beside them names `discoveryAccounts` exactly.",
    ),
    (
        "data/AgentChatLambdaRole",
        "Bedrock model and knowledge-base ARNs, left wildcarded deliberately: the usable "
        "form depends on whether the deployment calls a foundation model, an inference "
        "profile or a cross-region profile, and a narrowing that guesses wrong disables the "
        "AI features silently rather than failing at deploy. See "
        "`docs/bedrock-inference-profiles.md`.",
    ),
    (
        "data/SearchFilesLambdaRole",
        "A Bedrock knowledge-base ARN, for the same reason as `AgentChatLambdaRole`. The S3 "
        "read beside it goes through the same path scoping as the keyword search.",
    ),
    (
        "data/ResourceMgmtLambdaRole",
        "`s3:ListAllMyBuckets` is account-level and defines no resource type; it sits in a "
        "statement of its own so that the bucket-level actions beside it are not held open "
        "with it. Those name `s3ObjectLockBucket` once it is configured, and it is unset in "
        "`portal-config.example.ts`, which is what this baseline is measured against.",
    ),
    (
        "data/QueryAuditLogLambdaRole",
        "Reading the CloudTrail objects the query scans: Athena reads them with this role's "
        "credentials, and the bucket holding them is not portal configuration -- it is "
        "wherever the Glue table's `Location` points, set up outside this stack. The Athena "
        "workgroup, database and table beside it are named exactly, and the output location "
        "is named once `ATHENA_AUDIT_OUTPUT` is set.",
    ),
    (
        "data/GetFileMetadataLambdaRole",
        "The AI metadata table, which the portal does not create -- an operator names an "
        "existing one, and it is unset in `portal-config.example.ts`. Named once set; `*` "
        "while unset, because an ARN built from an empty name addresses no table and would "
        "deny every read as though the grant were broken.",
    ),
    (
        "data/",
        "A resource wildcard on a Lambda role we declare. What remains is object keys, "
        "which cannot be listed in advance, and names that arrive as configuration -- see "
        "`amplify/least-privilege-arns.ts` for the ARNs that replaced the rest, and for "
        "which actions were checked against the service authorization reference to "
        "establish that they can carry no resource at all.",
    ),
]


# Why an IAM4 finding is recorded on a role we declare. It is one cause -- the role carries
# an AWS managed execution policy -- and the per-role entries in `REASONS` explain resource
# wildcards, which is a different question. Reading a role's IAM5 reason onto its IAM4
# finding would claim the managed policy was chosen for reasons about ARNs.
MANAGED_POLICY_REASON = (
    "An AWS managed execution policy on a Lambda role we declare: "
    "`AWSLambdaBasicExecutionRole` for CloudWatch Logs, and "
    "`AWSLambdaVPCAccessExecutionRole` on the one function that reaches the ONTAP "
    "management LIF. Both are the AWS-recommended policy for what they grant. Replacing "
    "the logs one with an inline policy needs the log group name, which derives from the "
    "function name CDK generates -- so the wildcard moves from the policy to the resource "
    "rather than going away."
)

# Paths whose findings belong to whoever generated the construct, IAM4 included. Checked
# before the rule, because `MANAGED_POLICY_REASON` says "a role we declare" and these are
# roles Amplify and the CDK construct library declare.
GENERATED_ELSEWHERE = ("auth/", "data/amplifyData", "data/Custom::CDK", "data/LogRetention")


def reason_for(path: str, rule: str = "") -> str:
    """The recorded reason for a finding.

    `rule` participates because one construct produces findings with unrelated causes: a
    role's resource wildcard and the managed policy attached to it are both reported
    against the role, and only the first is about what the role may reach.
    """
    generated = any(path.startswith(p) or p in path for p in GENERATED_ELSEWHERE)
    if rule.startswith("AwsSolutions-IAM4") and not generated:
        return MANAGED_POLICY_REASON
    for prefix, reason in REASONS:
        if path.startswith(prefix) or prefix in path:
            return reason
    return "uncategorised"


def run_nag() -> None:
    """Synthesise with cdk-nag. Does not deploy."""
    print("Running npm run nag (synthesises, does not deploy)...", file=sys.stderr)
    # The script exits non-zero while findings remain, which is the normal state and not
    # a reason to stop here: the report it writes is what this check reads.
    subprocess.run(
        ["npm", "run", "--silent", "nag"],
        cwd=PORTAL,
        check=False,
        capture_output=True,
        text=True,
    )


def current_findings() -> set[tuple[str, str]]:
    """Every (rule, construct path) cdk-nag reports, with the stack prefix removed.

    The stack name carries a hash of the backend identifier, which differs between a
    sandbox and CI, so it cannot be part of a finding's identity.
    """
    if not REPORT.is_file():
        run_nag()
    if not REPORT.is_file():
        raise SystemExit(f"no validation report at {REPORT}; run `npm run nag` in {PORTAL}")
    report = json.loads(REPORT.read_text())
    found: set[tuple[str, str]] = set()
    for plugin in report.get("pluginReports", []):
        for violation in plugin.get("violations", []):
            for construct in violation.get("violatingConstructs", []):
                path = construct["constructPath"]
                found.add((violation["ruleName"], path.split("/", 1)[1] if "/" in path else path))
    return found


def read_baseline() -> set[tuple[str, str]]:
    """The recorded findings. Empty when the file is absent."""
    if not BASELINE.is_file():
        return set()
    entries: set[tuple[str, str]] = set()
    for line in BASELINE.read_text().splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        rule, _, path = line.partition("\t")
        entries.add((rule, path))
    return entries


def write_baseline(findings: set[tuple[str, str]]) -> None:
    """Rewrite the baseline, grouped by reason so the diff is readable."""
    by_reason: dict[str, list[tuple[str, str]]] = {}
    for rule, path in findings:
        by_reason.setdefault(reason_for(path, rule), []).append((rule, path))
    lines = [
        "# cdk-nag findings recorded as known, one per line: <rule id>\\t<construct path>.",
        "#",
        "# Generated by `python3 scripts/check_cdk_nag_baseline.py --write`. A finding that",
        "# is not here fails the build, and an entry no longer reported fails too, so this",
        "# cannot drift upward or hide progress.",
        "#",
        "# The construct path has the stack name removed: it carries a hash of the backend",
        "# identifier, which differs between a sandbox and CI.",
        "#",
        "# A recorded finding is not a fixed one. The reason above each group is the whole",
        "# of what is claimed about it; see scripts/check_cdk_nag_baseline.py.",
    ]
    for reason in sorted(by_reason):
        lines.append("")
        for wrapped in _wrap(reason, 86):
            lines.append(f"# {wrapped}")
        for rule, path in sorted(by_reason[reason]):
            lines.append(f"{rule}\t{path}")
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    BASELINE.write_text("\n".join(lines) + "\n")


def _wrap(text: str, width: int) -> list[str]:
    """Wrap without importing textwrap, to keep the comment style predictable."""
    out: list[str] = []
    line = ""
    for word in text.split():
        if line and len(line) + 1 + len(word) > width:
            out.append(line)
            line = word
        else:
            line = f"{line} {word}".strip()
    if line:
        out.append(line)
    return out


def main(argv: list[str] | None = None) -> int:
    """Compare the report against the baseline.

    Args:
        argv: Arguments to parse. Defaults to the process arguments; passed explicitly by
            the tests, which would otherwise have pytest's own arguments parsed here.

    Returns:
        0 when the two agree, 1 when a finding is new, has been fixed without the baseline
        being refreshed, or no baseline is recorded at all.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--list", action="store_true", help="print what is reported now")
    parser.add_argument("--write", action="store_true", help="rewrite the baseline file")
    args = parser.parse_args(argv)

    findings = current_findings()

    if args.list:
        for rule, path in sorted(findings):
            print(f"{rule}\t{path}")
        print(f"\n{len(findings)} finding(s)", file=sys.stderr)
        return 0

    if args.write:
        write_baseline(findings)
        print(f"CDK-NAG BASELINE: wrote {len(findings)} finding(s) to {BASELINE.relative_to(ROOT)}")
        return 0

    baseline = read_baseline()
    if not baseline:
        print(
            "CDK-NAG BASELINE: FAIL (no baseline recorded; "
            "run `python3 scripts/check_cdk_nag_baseline.py --write` and read the diff)",
            file=sys.stderr,
        )
        return 1

    new = sorted(findings - baseline)
    fixed = sorted(baseline - findings)
    if new:
        print(f"CDK-NAG BASELINE: FAIL ({len(new)} finding(s) not in the baseline)")
        for rule, path in new:
            print(f"  NEW {rule}\n      {path}")
        print(
            "\nFix it, or record it with --write and say in the commit why it is acceptable.",
            file=sys.stderr,
        )
        return 1
    if fixed:
        print(f"CDK-NAG BASELINE: FAIL ({len(fixed)} baseline finding(s) no longer reported)")
        for rule, path in fixed:
            print(f"  GONE {rule}\n       {path}")
        print(
            "\nProgress the baseline does not know about. Refresh it with --write.",
            file=sys.stderr,
        )
        return 1

    print(f"CDK-NAG BASELINE: PASS ({len(findings)} known finding(s) at the baseline)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
