#!/usr/bin/env python3
"""Hold cdk-nag to a baseline, so a new finding fails instead of joining a pile.

Why a baseline rather than a clean run
--------------------------------------
cdk-nag reported 108 findings on the portal backend and nothing consumed the number, so
it was a report nobody read. Two of the categories were fixed rather than recorded
(point-in-time recovery on the two tables holding authored content, and a TLS-only policy
on the alarm topic). The rest need either a decision that cannot be validated without
deploying, or a change to a resource Amplify owns.

Recording them makes the remainder blocking: a finding that is not in the baseline fails,
and a baseline entry that is no longer reported also fails, so the file cannot drift
upward or hide progress. Same shape as `scripts/check_cfn_guard.py`.

What this does not claim
------------------------
A baselined finding is not a fixed finding. The `REASONS` table below says which
category each belongs to and why it is where it is; "Amplify owns the resource" and "we
own it and have not narrowed it yet" are different statements and are kept apart.

Running it
----------
    python3 scripts/check_cdk_nag_baseline.py            # blocking
    python3 scripts/check_cdk_nag_baseline.py --list     # what is reported now
    python3 scripts/check_cdk_nag_baseline.py --write    # rewrite the baseline file

`--write` is for after a deliberate change. Read the diff: it is the only place a new
finding can enter without failing.

The report comes from `solutions/amplify-portal/scripts/cdk-nag.sh` (`npm run nag`), which
synthesises without deploying. This script runs it when the report is missing or stale.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PORTAL = ROOT / "solutions" / "amplify-portal"
REPORT = PORTAL / ".cdk-nag-out" / "validation-report.json"
BASELINE = ROOT / "security" / "cdk-nag-baseline.txt"

# Which category a construct path belongs to, and why its findings are recorded rather
# than fixed. Ordered: the first matching prefix wins.
#
# Written as categories rather than per-finding notes because the findings arrive in
# groups -- nineteen Lambda roles carry the same managed policy for the same reason -- and
# a hundred copies of one sentence is not more informative than one.
REASONS: list[tuple[str, str]] = [
    # Before the generic `auth/` entry below, which would otherwise claim these are
    # Cognito settings Amplify owns. They are our own grant, on roles Amplify creates but
    # `backend.ts` fills in, and saying otherwise would misattribute eighteen findings.
    (
        "auth/amplifyAuth/authenticatedUserRole",
        "The Storage Browser's S3 scope, which is `s3ApResourceArns` from "
        "`portal-config.ts`. The account and region are filled in from the deployment, so "
        "what remains wildcarded is the access point name and the object key. A key cannot "
        "be enumerated in advance; an access-point wildcard is refused at synth once "
        "`groupApMapping` is in use.",
    ),
    (
        "GroupRole",
        "A Cognito group role, whose S3 grant `backend.ts` writes from `s3ApResourceArns` "
        "-- see `amplify/direct-s3-access.ts` for which group gets what. Same wildcards as "
        "the authenticated role above, and the same reasons.",
    ),
    (
        "auth/",
        "Cognito configured by Amplify `defineAuth`. MFA is a deployment choice exposed "
        "as `signIn.mfa`; the advanced-security and password-policy rules cover settings "
        "Amplify does not surface.",
    ),
    (
        "data/amplifyData",
        "AppSync and its table manager are generated by Amplify `defineData`. The "
        "wildcards are in roles Amplify writes, scoped to resources whose names are only "
        "known at deploy time.",
    ),
    (
        "data/AmplifyTableManager",
        "Same as data/amplifyData: an Amplify-generated custom resource.",
    ),
    (
        "data/Custom::CDK",
        "A CDK-internal custom resource (bucket deployment, log retention). Its role is "
        "written by the construct library.",
    ),
    (
        "data/LogRetention",
        "A CDK-internal custom resource. Its role is written by the construct library.",
    ),
    (
        "data/ChatHistoryTable",
        "No point-in-time recovery, deliberately: the rows carry a TTL and are chat "
        "history the portal regenerates as people use it. The two tables holding authored "
        "content -- agent definitions and team compositions -- do have it.",
    ),
    (
        "data/PortalSettingsTable",
        "No point-in-time recovery, deliberately: the table holds feature gates, so "
        "losing it resets them to their defaults and an administrator sets them again.",
    ),
    (
        "data/",
        "A Lambda role we declare. `AWSLambdaBasicExecutionRole` is the AWS-recommended "
        "execution policy; the resource wildcards cover ARNs resolved at deploy time "
        "(tables, secrets, Bedrock models) and object keys that cannot be listed in "
        "advance. Narrowing each needs a per-endpoint review that has not been done.",
    ),
]


def reason_for(path: str) -> str:
    """The recorded reason for a finding on `path`."""
    for prefix, reason in REASONS:
        if path.startswith(prefix) or prefix in path:
            return reason
    return "uncategorised"


def run_nag() -> None:
    """Synthesise with cdk-nag. Does not deploy."""
    print("Running npm run nag (synthesises, does not deploy)...", file=sys.stderr)
    # The script exits non-zero while findings remain, which is the normal state and not
    # a reason to stop here: the report it writes is what this check reads.
    subprocess.run(
        ["npm", "run", "--silent", "nag"],
        cwd=PORTAL,
        check=False,
        capture_output=True,
        text=True,
    )


def current_findings() -> set[tuple[str, str]]:
    """Every (rule, construct path) cdk-nag reports, with the stack prefix removed.

    The stack name carries a hash of the backend identifier, which differs between a
    sandbox and CI, so it cannot be part of a finding's identity.
    """
    if not REPORT.is_file():
        run_nag()
    if not REPORT.is_file():
        raise SystemExit(f"no validation report at {REPORT}; run `npm run nag` in {PORTAL}")
    report = json.loads(REPORT.read_text())
    found: set[tuple[str, str]] = set()
    for plugin in report.get("pluginReports", []):
        for violation in plugin.get("violations", []):
            for construct in violation.get("violatingConstructs", []):
                path = construct["constructPath"]
                found.add((violation["ruleName"], path.split("/", 1)[1] if "/" in path else path))
    return found


def read_baseline() -> set[tuple[str, str]]:
    """The recorded findings. Empty when the file is absent."""
    if not BASELINE.is_file():
        return set()
    entries: set[tuple[str, str]] = set()
    for line in BASELINE.read_text().splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        rule, _, path = line.partition("\t")
        entries.add((rule, path))
    return entries


def write_baseline(findings: set[tuple[str, str]]) -> None:
    """Rewrite the baseline, grouped by reason so the diff is readable."""
    by_reason: dict[str, list[tuple[str, str]]] = {}
    for rule, path in findings:
        by_reason.setdefault(reason_for(path), []).append((rule, path))
    lines = [
        "# cdk-nag findings recorded as known, one per line: <rule id>\\t<construct path>.",
        "#",
        "# Generated by `python3 scripts/check_cdk_nag_baseline.py --write`. A finding that",
        "# is not here fails the build, and an entry no longer reported fails too, so this",
        "# cannot drift upward or hide progress.",
        "#",
        "# The construct path has the stack name removed: it carries a hash of the backend",
        "# identifier, which differs between a sandbox and CI.",
        "#",
        "# A recorded finding is not a fixed one. The reason above each group is the whole",
        "# of what is claimed about it; see scripts/check_cdk_nag_baseline.py.",
    ]
    for reason in sorted(by_reason):
        lines.append("")
        for wrapped in _wrap(reason, 86):
            lines.append(f"# {wrapped}")
        for rule, path in sorted(by_reason[reason]):
            lines.append(f"{rule}\t{path}")
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    BASELINE.write_text("\n".join(lines) + "\n")


def _wrap(text: str, width: int) -> list[str]:
    """Wrap without importing textwrap, to keep the comment style predictable."""
    out: list[str] = []
    line = ""
    for word in text.split():
        if line and len(line) + 1 + len(word) > width:
            out.append(line)
            line = word
        else:
            line = f"{line} {word}".strip()
    if line:
        out.append(line)
    return out


def main(argv: list[str] | None = None) -> int:
    """Compare the report against the baseline.

    Args:
        argv: Arguments to parse. Defaults to the process arguments; passed explicitly by
            the tests, which would otherwise have pytest's own arguments parsed here.

    Returns:
        0 when the two agree, 1 when a finding is new, has been fixed without the baseline
        being refreshed, or no baseline is recorded at all.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--list", action="store_true", help="print what is reported now")
    parser.add_argument("--write", action="store_true", help="rewrite the baseline file")
    args = parser.parse_args(argv)

    findings = current_findings()

    if args.list:
        for rule, path in sorted(findings):
            print(f"{rule}\t{path}")
        print(f"\n{len(findings)} finding(s)", file=sys.stderr)
        return 0

    if args.write:
        write_baseline(findings)
        print(f"CDK-NAG BASELINE: wrote {len(findings)} finding(s) to {BASELINE.relative_to(ROOT)}")
        return 0

    baseline = read_baseline()
    if not baseline:
        print(
            "CDK-NAG BASELINE: FAIL (no baseline recorded; "
            "run `python3 scripts/check_cdk_nag_baseline.py --write` and read the diff)",
            file=sys.stderr,
        )
        return 1

    new = sorted(findings - baseline)
    fixed = sorted(baseline - findings)
    if new:
        print(f"CDK-NAG BASELINE: FAIL ({len(new)} finding(s) not in the baseline)")
        for rule, path in new:
            print(f"  NEW {rule}\n      {path}")
        print(
            "\nFix it, or record it with --write and say in the commit why it is acceptable.",
            file=sys.stderr,
        )
        return 1
    if fixed:
        print(f"CDK-NAG BASELINE: FAIL ({len(fixed)} baseline finding(s) no longer reported)")
        for rule, path in fixed:
            print(f"  GONE {rule}\n       {path}")
        print(
            "\nProgress the baseline does not know about. Refresh it with --write.",
            file=sys.stderr,
        )
        return 1

    print(f"CDK-NAG BASELINE: PASS ({len(findings)} known finding(s) at the baseline)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
