#!/bin/bash
# Export the architecture diagrams to SVG + PNG@2x.
#
# NOTE: draw.io Desktop is installed but its CLI is NOT on PATH as `drawio`,
# so we call the binary inside the .app directly.
set -euo pipefail

DRAWIO="/Applications/draw.io.app/Contents/MacOS/draw.io"
SRC_DIR="docs/diagrams"
DARK_SRC_DIR="docs/diagrams/dark"
OUT_DIR="docs/images"
PNG_DIR="docs/images/png"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if [[ ! -d "$SRC_DIR" ]]; then
  echo "ERROR: $SRC_DIR not found (resolved repo root: $REPO_ROOT)" >&2
  exit 1
fi

mkdir -p "$OUT_DIR" "$PNG_DIR"

# source basename -> published output name (kebab-case, versionless).
# The Japanese diagrams are the source of truth; `<name>-en.drawio` variants are
# generated by scripts/generate-en-diagrams.py and keep the same `-en` suffix on
# their output.
#
# There used to be a rename map here: four Part1 sources were named `file-portal-*`
# and `nextcloud-only-*` while their exports carried the names the documents and the
# published articles reference. Two names for one figure cost more than it looked.
# scripts/check_diagram_fonts.py finds an export by matching the source's stem, so for
# those four it found nothing and fell back to `pageWidth` -- which is the page, not
# the picture. draw.io crops to content and adds a border, so the real exports are 1190
# to 2214px wide against pageWidth values of 900 to 1500, and the gate was reporting
# those figures at 6.5 to 10.8px when a reader receives them at 4.4 to 8.1px.
#
# The sources are renamed to match their exports instead. Do not reintroduce a map: the
# font gate is kept byte-identical across these repositories, so it cannot be taught a
# per-repository naming convention, and a gate measuring the wrong width is worse than
# no gate.
export_one() {
  local src="$1" out="$2"
  "$DRAWIO" --export --format svg --embed-svg-images --border 12 \
    --output "$OUT_DIR/${out}.svg" "$src" >/dev/null 2>&1

  "$DRAWIO" --export --format png --scale 2 --border 12 \
    --output "$PNG_DIR/${out}@2x.png" "$src" >/dev/null 2>&1
}

# Light theme: the primary published assets.
for src in "$SRC_DIR"/*.drawio; do
  base="$(basename "$src" .drawio)"
  out="$base"
  echo "==> $base -> $out"
  export_one "$src" "$out"
done

# Dark theme: generated by scripts/make-dark-diagrams.py into docs/diagrams/dark/,
# published alongside the light set with a `-dark` suffix. Not picked up by the
# loop above because that glob does not descend into subdirectories.
if compgen -G "$DARK_SRC_DIR/*.drawio" >/dev/null; then
  for src in "$DARK_SRC_DIR"/*.drawio; do
    base="$(basename "$src" .drawio)"
    out="${base}-dark"
    echo "==> dark/$base -> $out"
    export_one "$src" "$out"
  done
else
  echo "NOTE: no dark sources yet; run scripts/make-dark-diagrams.py --icon-root <dir>" >&2
fi

# draw.io emits a theme-adaptive SVG, but the embedded AWS icons are fixed artwork
# and do not adapt, so a viewer-flipped canvas leaves them illegible. Pin every SVG
# to the theme its source authored. (PNG export is already opaque.)
echo "==> pinning SVGs to their authored theme"
python3 "${REPO_ROOT}/scripts/pin-svg-theme.py" "$OUT_DIR"/*.svg

echo "--- results ---"
ls -la "$OUT_DIR"/*.svg "$PNG_DIR"/*.png 2>/dev/null
