import { describe, it, expect } from "vitest";
import {
  readEnforceRoles,
  readExternalAiEnabled,
  readExternalShareLinksByRole,
} from "../../src/lib/portalOutputs";

/**
 * What the UI assumes when the backend has told it nothing.
 *
 * Absent is the ordinary case, not an edge one: `amplify_outputs.json` is generated by
 * `npx ampx sandbox` and excluded by .gitignore, so it is missing in a fresh clone and
 * in CI, and any deployment made before these values were published omits them.
 *
 * Each default is asserted in the direction that fails safe. The inline form these
 * replaced -- `outputs.custom?.enforceRoles !== "false"` -- could be inverted to
 * `=== "true"` without any test noticing, and the inverted version shows write controls
 * to every account in exactly the deployments that publish nothing.
 */
describe("readEnforceRoles", () => {
  it("assumes the rules are on when the value is absent", () => {
    expect(readEnforceRoles(undefined)).toBe(true);
  });

  it("is off only for the literal false", () => {
    expect(readEnforceRoles("false")).toBe(false);
  });

  it("treats anything else as on", () => {
    // A misspelling used to switch the rules off. It must not any more: the value that
    // removes a restriction has to be written exactly.
    expect(readEnforceRoles("flase")).toBe(true);
    expect(readEnforceRoles("")).toBe(true);
    expect(readEnforceRoles("0")).toBe(true);
    expect(readEnforceRoles("no")).toBe(true);
  });
});

describe("readExternalAiEnabled", () => {
  it("is off when the value is absent", () => {
    expect(readExternalAiEnabled(undefined)).toBe(false);
  });

  it("is on only for the literal true", () => {
    expect(readExternalAiEnabled("true")).toBe(true);
    expect(readExternalAiEnabled("ture")).toBe(false);
    expect(readExternalAiEnabled("1")).toBe(false);
    expect(readExternalAiEnabled("yes")).toBe(false);
  });
});

describe("readExternalShareLinksByRole", () => {
  it("denies everything when the value is absent", () => {
    expect(readExternalShareLinksByRole(undefined)).toEqual({});
  });

  it("denies everything when the value will not parse", () => {
    expect(readExternalShareLinksByRole("{contributor: true}")).toEqual({});
    expect(readExternalShareLinksByRole("")).toEqual({});
  });

  it("denies everything when the value is not an object", () => {
    // `JSON.parse` accepts these, and an array would make `mapping[role]` undefined for
    // every role -- the same answer, reached by accident rather than on purpose.
    expect(readExternalShareLinksByRole("null")).toEqual({});
    expect(readExternalShareLinksByRole("true")).toEqual({});
    expect(readExternalShareLinksByRole('["contributor"]')).toEqual({});
  });

  it("keeps the mapping it was given", () => {
    expect(readExternalShareLinksByRole('{"contributor":true,"viewer":false}')).toEqual({
      contributor: true,
      viewer: false,
    });
  });
});
