/**
 * Values the backend publishes to the browser through `amplify_outputs.json`.
 *
 * `backend.addOutput({ custom: ... })` in `amplify/backend.ts` writes them, so
 * the environment is described in exactly one place: `amplify/portal-config.ts`.
 *
 * `amplify_outputs.json` is generated by `npx ampx sandbox` and excluded by
 * .gitignore, so it is absent in a fresh clone and in CI. A static import would
 * fail to resolve there and break the build, which is why this reads the file
 * through `import.meta.glob` instead: the glob yields an empty record when the
 * file is missing, and the callers below fall back to "" -- the value the UI
 * already treats as "not configured".
 */

type CustomOutputs = {
  s3ApAlias?: string;
  region?: string;
};

type AmplifyOutputs = {
  custom?: CustomOutputs;
  auth?: { aws_region?: string };
};

const found = import.meta.glob<{ default: AmplifyOutputs }>("../../amplify_outputs.json", {
  eager: true,
});

const outputs: AmplifyOutputs = Object.values(found)[0]?.default ?? {};

/**
 * S3 AP alias (or plain bucket name in DemoMode) that the Upload tab browses.
 * Empty when the backend has not been deployed, or when `s3ApAlias` is unset in
 * `amplify/portal-config.ts`.
 */
export const s3ApAlias: string = outputs.custom?.s3ApAlias ?? "";

/**
 * Region used for the browser's direct S3 calls. Falls back to the region Amplify
 * already records for Cognito, since the two are the same deployment.
 */
export const outputsRegion: string = outputs.custom?.region ?? outputs.auth?.aws_region ?? "";
