import React from "react";
import ReactDOM from "react-dom/client";
import { Amplify } from "aws-amplify";
import { Authenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";
import App from "./App";
import "./index.css";

// Configure Amplify with generated outputs
// This file is auto-generated by `npx ampx sandbox` or `npx ampx generate outputs`
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - amplify_outputs.json may not exist before first sandbox deploy
import outputs from "../amplify_outputs.json";
Amplify.configure(outputs);

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <Authenticator>
      <App />
    </Authenticator>
  </React.StrictMode>
);
